import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#bec8ce",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "outline": "#899298",
        "outline-variant": "#3f484e",
        "surface-tint": "#7bd1fa",
        "primary": "#c5eaff",
        "on-primary": "#003547",
        "primary-container": "#7dd3fc",
        "on-primary-container": "#005b78",
        "inverse-primary": "#006686",
        "secondary": "#5adcb3",
        "on-secondary": "#003829",
        "secondary-container": "#00a782",
        "on-secondary-container": "#003326",
        "tertiary": "#e7e4e3",
        "on-tertiary": "#313030",
        "tertiary-container": "#cbc8c7",
        "on-tertiary-container": "#555453",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#c0e8ff",
        "primary-fixed-dim": "#7bd1fa",
        "on-primary-fixed": "#001e2b",
        "on-primary-fixed-variant": "#004d66",
        "secondary-fixed": "#79f9ce",
        "secondary-fixed-dim": "#5adcb3",
        "on-secondary-fixed": "#002117",
        "on-secondary-fixed-variant": "#00513d",
        "tertiary-fixed": "#e5e2e1",
        "tertiary-fixed-dim": "#c9c6c5",
        "on-tertiary-fixed": "#1c1b1b",
        "on-tertiary-fixed-variant": "#474646",
        "background": "#131313",
        "on-background": "#e5e2e1",
        "surface-variant": "#353534",
        "base": "#050505",
        "grid-line": "#1a1a1a",
        "field": "#050505",
        "field-border": "#262626",
      },
      borderRadius: {
        DEFAULT: "0px",
        none: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        gutter: "1px",
        "panel-margin": "12px",
      },
      fontFamily: {
        sans: ["var(--font-geist-sans)", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "ui-monospace", "monospace"],
        "display": ["var(--font-geist-sans)"],
        "headline-lg": ["var(--font-geist-sans)"],
        "headline-md": ["var(--font-geist-sans)"],
        "body-lg": ["var(--font-geist-sans)"],
        "body-md": ["var(--font-geist-sans)"],
        "code-lg": ["var(--font-mono)"],
        "code-md": ["var(--font-mono)"],
        "label-caps": ["var(--font-mono)"],
      },
      fontSize: {
        "display": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "code-lg": ["14px", { lineHeight: "1.7", fontWeight: "400" }],
        "code-md": ["13px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
